# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

struct EditsApi <: OpenAPI.APIClientImpl
    client::OpenAPI.Clients.Client
end

"""
The default API base path for APIs in `EditsApi`.
This can be used to construct the `OpenAPI.Clients.Client` instance.
"""
basepath(::Type{ EditsApi }) = "https://api.openai.com/v1"

const _returntypes_create_edit_EditsApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => CreateEditResponse,
)

function _oacinternal_create_edit(_api::EditsApi, create_edit_request::CreateEditRequest; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "POST", _returntypes_create_edit_EditsApi, "/edits", ["ApiKeyAuth", ], create_edit_request)
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json", ] : [_mediaType])
    return _ctx
end

@doc raw"""Creates a new edit for the provided input, instruction, and parameters.

Params:
- create_edit_request::CreateEditRequest (required)

Return: CreateEditResponse, OpenAPI.Clients.ApiResponse
"""
function create_edit(_api::EditsApi, create_edit_request::CreateEditRequest; _mediaType=nothing)
    _ctx = _oacinternal_create_edit(_api, create_edit_request; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function create_edit(_api::EditsApi, response_stream::Channel, create_edit_request::CreateEditRequest; _mediaType=nothing)
    _ctx = _oacinternal_create_edit(_api, create_edit_request; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

export create_edit
