# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

struct ChatApi <: OpenAPI.APIClientImpl
    client::OpenAPI.Clients.Client
end

"""
The default API base path for APIs in `ChatApi`.
This can be used to construct the `OpenAPI.Clients.Client` instance.
"""
basepath(::Type{ ChatApi }) = "https://api.openai.com/v1"

const _returntypes_create_chat_completion_ChatApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => CreateChatCompletionResponse,
)

function _oacinternal_create_chat_completion(_api::ChatApi, create_chat_completion_request::CreateChatCompletionRequest; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "POST", _returntypes_create_chat_completion_ChatApi, "/chat/completions", ["ApiKeyAuth", ], create_chat_completion_request)
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json", ] : [_mediaType])
    return _ctx
end

@doc raw"""Creates a model response for the given chat conversation.

Params:
- create_chat_completion_request::CreateChatCompletionRequest (required)

Return: CreateChatCompletionResponse, OpenAPI.Clients.ApiResponse
"""
function create_chat_completion(_api::ChatApi, create_chat_completion_request::CreateChatCompletionRequest; _mediaType=nothing)
    _ctx = _oacinternal_create_chat_completion(_api, create_chat_completion_request; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function create_chat_completion(_api::ChatApi, response_stream::Channel, create_chat_completion_request::CreateChatCompletionRequest; _mediaType=nothing)
    _ctx = _oacinternal_create_chat_completion(_api, create_chat_completion_request; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

export create_chat_completion
