# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.



@doc raw"""ChatCompletionRequestMessageContentPart

    ChatCompletionRequestMessageContentPart(; value=nothing)
"""
mutable struct ChatCompletionRequestMessageContentPart <: OpenAPI.OneOfAPIModel
    value::Any # Union{ ChatCompletionRequestMessageContentPartImage, ChatCompletionRequestMessageContentPartText }
    ChatCompletionRequestMessageContentPart() = new()
    ChatCompletionRequestMessageContentPart(value) = new(value)
end # type ChatCompletionRequestMessageContentPart

function OpenAPI.property_type(::Type{ ChatCompletionRequestMessageContentPart }, name::Symbol, json::Dict{String,Any})
    
    # no discriminator specified, can't determine the exact type
    return fieldtype(ChatCompletionRequestMessageContentPart, name)
end
