# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""CreateModerationRequest

    CreateModerationRequest(;
        input=nothing,
        model=nothing,
    )

    - input::CreateModerationRequestInput
    - model::CreateModerationRequestModel
"""
Base.@kwdef mutable struct CreateModerationRequest <: OpenAPI.APIModel
    input = nothing # spec type: Union{ Nothing, CreateModerationRequestInput }
    model = nothing # spec type: Union{ Nothing, CreateModerationRequestModel }

    function CreateModerationRequest(input, model, )
        OpenAPI.validate_property(CreateModerationRequest, Symbol("input"), input)
        OpenAPI.validate_property(CreateModerationRequest, Symbol("model"), model)
        return new(input, model, )
    end
end # type CreateModerationRequest

const _property_types_CreateModerationRequest = Dict{Symbol,String}(Symbol("input")=>"CreateModerationRequestInput", Symbol("model")=>"CreateModerationRequestModel", )
OpenAPI.property_type(::Type{ CreateModerationRequest }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_CreateModerationRequest[name]))}

function check_required(o::CreateModerationRequest)
    o.input === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ CreateModerationRequest }, name::Symbol, val)
end
