# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""AssistantObject
Represents an &#x60;assistant&#x60; that can call the model and use tools.

    AssistantObject(;
        id=nothing,
        object=nothing,
        created_at=nothing,
        name=nothing,
        description=nothing,
        model=nothing,
        instructions=nothing,
        tools=nothing,
        file_ids=nothing,
        metadata=nothing,
    )

    - id::String : The identifier, which can be referenced in API endpoints.
    - object::String : The object type, which is always &#x60;assistant&#x60;.
    - created_at::Int64 : The Unix timestamp (in seconds) for when the assistant was created.
    - name::String : The name of the assistant. The maximum length is 256 characters. 
    - description::String : The description of the assistant. The maximum length is 512 characters. 
    - model::String : ID of the model to use. You can use the [List models](/docs/api-reference/models/list) API to see all of your available models, or see our [Model overview](/docs/models/overview) for descriptions of them. 
    - instructions::String : The system instructions that the assistant uses. The maximum length is 32768 characters. 
    - tools::Vector{AssistantObjectToolsInner} : A list of tool enabled on the assistant. There can be a maximum of 128 tools per assistant. Tools can be of types &#x60;code_interpreter&#x60;, &#x60;retrieval&#x60;, or &#x60;function&#x60;. 
    - file_ids::Vector{String} : A list of [file](/docs/api-reference/files) IDs attached to this assistant. There can be a maximum of 20 files attached to the assistant. Files are ordered by their creation date in ascending order. 
    - metadata::Any : Set of 16 key-value pairs that can be attached to an object. This can be useful for storing additional information about the object in a structured format. Keys can be a maximum of 64 characters long and values can be a maxium of 512 characters long. 
"""
Base.@kwdef mutable struct AssistantObject <: OpenAPI.APIModel
    id::Union{Nothing, String} = nothing
    object::Union{Nothing, String} = nothing
    created_at::Union{Nothing, Int64} = nothing
    name::Union{Nothing, String} = nothing
    description::Union{Nothing, String} = nothing
    model::Union{Nothing, String} = nothing
    instructions::Union{Nothing, String} = nothing
    tools::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{AssistantObjectToolsInner} }
    file_ids::Union{Nothing, Vector{String}} = nothing
    metadata::Union{Nothing, Any} = nothing

    function AssistantObject(id, object, created_at, name, description, model, instructions, tools, file_ids, metadata, )
        OpenAPI.validate_property(AssistantObject, Symbol("id"), id)
        OpenAPI.validate_property(AssistantObject, Symbol("object"), object)
        OpenAPI.validate_property(AssistantObject, Symbol("created_at"), created_at)
        OpenAPI.validate_property(AssistantObject, Symbol("name"), name)
        OpenAPI.validate_property(AssistantObject, Symbol("description"), description)
        OpenAPI.validate_property(AssistantObject, Symbol("model"), model)
        OpenAPI.validate_property(AssistantObject, Symbol("instructions"), instructions)
        OpenAPI.validate_property(AssistantObject, Symbol("tools"), tools)
        OpenAPI.validate_property(AssistantObject, Symbol("file_ids"), file_ids)
        OpenAPI.validate_property(AssistantObject, Symbol("metadata"), metadata)
        return new(id, object, created_at, name, description, model, instructions, tools, file_ids, metadata, )
    end
end # type AssistantObject

const _property_types_AssistantObject = Dict{Symbol,String}(Symbol("id")=>"String", Symbol("object")=>"String", Symbol("created_at")=>"Int64", Symbol("name")=>"String", Symbol("description")=>"String", Symbol("model")=>"String", Symbol("instructions")=>"String", Symbol("tools")=>"Vector{AssistantObjectToolsInner}", Symbol("file_ids")=>"Vector{String}", Symbol("metadata")=>"Any", )
OpenAPI.property_type(::Type{ AssistantObject }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_AssistantObject[name]))}

function check_required(o::AssistantObject)
    o.id === nothing && (return false)
    o.object === nothing && (return false)
    o.created_at === nothing && (return false)
    o.name === nothing && (return false)
    o.description === nothing && (return false)
    o.model === nothing && (return false)
    o.instructions === nothing && (return false)
    o.tools === nothing && (return false)
    o.file_ids === nothing && (return false)
    o.metadata === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ AssistantObject }, name::Symbol, val)
    if name === Symbol("object")
        OpenAPI.validate_param(name, "AssistantObject", :enum, val, ["assistant"])
    end
    if name === Symbol("name")
        OpenAPI.validate_param(name, "AssistantObject", :maxLength, val, 256)
    end
    if name === Symbol("description")
        OpenAPI.validate_param(name, "AssistantObject", :maxLength, val, 512)
    end
    if name === Symbol("instructions")
        OpenAPI.validate_param(name, "AssistantObject", :maxLength, val, 32768)
    end
    if name === Symbol("tools")
        OpenAPI.validate_param(name, "AssistantObject", :maxItems, val, 128)
    end
    if name === Symbol("file_ids")
        OpenAPI.validate_param(name, "AssistantObject", :maxItems, val, 20)
    end
end
