# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""CreateChatCompletionFunctionResponse_choices_inner

    CreateChatCompletionFunctionResponseChoicesInner(;
        finish_reason=nothing,
        index=nothing,
        message=nothing,
    )

    - finish_reason::String : The reason the model stopped generating tokens. This will be &#x60;stop&#x60; if the model hit a natural stop point or a provided stop sequence, &#x60;length&#x60; if the maximum number of tokens specified in the request was reached, &#x60;content_filter&#x60; if content was omitted due to a flag from our content filters, or &#x60;function_call&#x60; if the model called a function. 
    - index::Int64 : The index of the choice in the list of choices.
    - message::ChatCompletionResponseMessage
"""
Base.@kwdef mutable struct CreateChatCompletionFunctionResponseChoicesInner <: OpenAPI.APIModel
    finish_reason::Union{Nothing, String} = nothing
    index::Union{Nothing, Int64} = nothing
    message = nothing # spec type: Union{ Nothing, ChatCompletionResponseMessage }

    function CreateChatCompletionFunctionResponseChoicesInner(finish_reason, index, message, )
        OpenAPI.validate_property(CreateChatCompletionFunctionResponseChoicesInner, Symbol("finish_reason"), finish_reason)
        OpenAPI.validate_property(CreateChatCompletionFunctionResponseChoicesInner, Symbol("index"), index)
        OpenAPI.validate_property(CreateChatCompletionFunctionResponseChoicesInner, Symbol("message"), message)
        return new(finish_reason, index, message, )
    end
end # type CreateChatCompletionFunctionResponseChoicesInner

const _property_types_CreateChatCompletionFunctionResponseChoicesInner = Dict{Symbol,String}(Symbol("finish_reason")=>"String", Symbol("index")=>"Int64", Symbol("message")=>"ChatCompletionResponseMessage", )
OpenAPI.property_type(::Type{ CreateChatCompletionFunctionResponseChoicesInner }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_CreateChatCompletionFunctionResponseChoicesInner[name]))}

function check_required(o::CreateChatCompletionFunctionResponseChoicesInner)
    o.finish_reason === nothing && (return false)
    o.index === nothing && (return false)
    o.message === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ CreateChatCompletionFunctionResponseChoicesInner }, name::Symbol, val)
    if name === Symbol("finish_reason")
        OpenAPI.validate_param(name, "CreateChatCompletionFunctionResponseChoicesInner", :enum, val, ["stop", "length", "function_call", "content_filter"])
    end
end
