# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.



@doc raw"""CreateEditRequest_model
ID of the model to use. You can use the &#x60;text-davinci-edit-001&#x60; or &#x60;code-davinci-edit-001&#x60; model with this endpoint.

    CreateEditRequestModel(; value=nothing)
"""
mutable struct CreateEditRequestModel <: OpenAPI.AnyOfAPIModel
    value::Any # Union{ String }
    CreateEditRequestModel() = new()
    CreateEditRequestModel(value) = new(value)
end # type CreateEditRequestModel

function OpenAPI.property_type(::Type{ CreateEditRequestModel }, name::Symbol, json::Dict{String,Any})
    
    # no discriminator specified, can't determine the exact type
    return fieldtype(CreateEditRequestModel, name)
end
