# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.



@doc raw"""CreateEmbeddingRequest_input
Input text to embed, encoded as a string or array of tokens. To embed multiple inputs in a single request, pass an array of strings or array of token arrays. The input must not exceed the max input tokens for the model (8192 tokens for &#x60;text-embedding-ada-002&#x60;), cannot be an empty string, and any array must be 2048 dimensions or less. [Example Python code](https://cookbook.openai.com/examples/how_to_count_tokens_with_tiktoken) for counting tokens. 

    CreateEmbeddingRequestInput(; value=nothing)
"""
mutable struct CreateEmbeddingRequestInput <: OpenAPI.OneOfAPIModel
    value::Any # Union{ String, Vector{Int64}, Vector{String}, Vector{Vector{Int64}} }
    CreateEmbeddingRequestInput() = new()
    CreateEmbeddingRequestInput(value) = new(value)
end # type CreateEmbeddingRequestInput

function OpenAPI.property_type(::Type{ CreateEmbeddingRequestInput }, name::Symbol, json::Dict{String,Any})
    
    # no discriminator specified, can't determine the exact type
    return fieldtype(CreateEmbeddingRequestInput, name)
end
