# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""MessageFileObject
A list of files attached to a &#x60;message&#x60;.

    MessageFileObject(;
        id=nothing,
        object=nothing,
        created_at=nothing,
        message_id=nothing,
    )

    - id::String : The identifier, which can be referenced in API endpoints.
    - object::String : The object type, which is always &#x60;thread.message.file&#x60;.
    - created_at::Int64 : The Unix timestamp (in seconds) for when the message file was created.
    - message_id::String : The ID of the [message](/docs/api-reference/messages) that the [File](/docs/api-reference/files) is attached to.
"""
Base.@kwdef mutable struct MessageFileObject <: OpenAPI.APIModel
    id::Union{Nothing, String} = nothing
    object::Union{Nothing, String} = nothing
    created_at::Union{Nothing, Int64} = nothing
    message_id::Union{Nothing, String} = nothing

    function MessageFileObject(id, object, created_at, message_id, )
        OpenAPI.validate_property(MessageFileObject, Symbol("id"), id)
        OpenAPI.validate_property(MessageFileObject, Symbol("object"), object)
        OpenAPI.validate_property(MessageFileObject, Symbol("created_at"), created_at)
        OpenAPI.validate_property(MessageFileObject, Symbol("message_id"), message_id)
        return new(id, object, created_at, message_id, )
    end
end # type MessageFileObject

const _property_types_MessageFileObject = Dict{Symbol,String}(Symbol("id")=>"String", Symbol("object")=>"String", Symbol("created_at")=>"Int64", Symbol("message_id")=>"String", )
OpenAPI.property_type(::Type{ MessageFileObject }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_MessageFileObject[name]))}

function check_required(o::MessageFileObject)
    o.id === nothing && (return false)
    o.object === nothing && (return false)
    o.created_at === nothing && (return false)
    o.message_id === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ MessageFileObject }, name::Symbol, val)
    if name === Symbol("object")
        OpenAPI.validate_param(name, "MessageFileObject", :enum, val, ["thread.message.file"])
    end
end
