# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""CreateFineTuningJobRequest_hyperparameters
The hyperparameters used for the fine-tuning job.

    CreateFineTuningJobRequestHyperparameters(;
        batch_size=nothing,
        learning_rate_multiplier=nothing,
        n_epochs=nothing,
    )

    - batch_size::CreateFineTuningJobRequestHyperparametersBatchSize
    - learning_rate_multiplier::CreateFineTuningJobRequestHyperparametersLearningRateMultiplier
    - n_epochs::CreateFineTuningJobRequestHyperparametersNEpochs
"""
Base.@kwdef mutable struct CreateFineTuningJobRequestHyperparameters <: OpenAPI.APIModel
    batch_size = nothing # spec type: Union{ Nothing, CreateFineTuningJobRequestHyperparametersBatchSize }
    learning_rate_multiplier = nothing # spec type: Union{ Nothing, CreateFineTuningJobRequestHyperparametersLearningRateMultiplier }
    n_epochs = nothing # spec type: Union{ Nothing, CreateFineTuningJobRequestHyperparametersNEpochs }

    function CreateFineTuningJobRequestHyperparameters(batch_size, learning_rate_multiplier, n_epochs, )
        OpenAPI.validate_property(CreateFineTuningJobRequestHyperparameters, Symbol("batch_size"), batch_size)
        OpenAPI.validate_property(CreateFineTuningJobRequestHyperparameters, Symbol("learning_rate_multiplier"), learning_rate_multiplier)
        OpenAPI.validate_property(CreateFineTuningJobRequestHyperparameters, Symbol("n_epochs"), n_epochs)
        return new(batch_size, learning_rate_multiplier, n_epochs, )
    end
end # type CreateFineTuningJobRequestHyperparameters

const _property_types_CreateFineTuningJobRequestHyperparameters = Dict{Symbol,String}(Symbol("batch_size")=>"CreateFineTuningJobRequestHyperparametersBatchSize", Symbol("learning_rate_multiplier")=>"CreateFineTuningJobRequestHyperparametersLearningRateMultiplier", Symbol("n_epochs")=>"CreateFineTuningJobRequestHyperparametersNEpochs", )
OpenAPI.property_type(::Type{ CreateFineTuningJobRequestHyperparameters }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_CreateFineTuningJobRequestHyperparameters[name]))}

function check_required(o::CreateFineTuningJobRequestHyperparameters)
    true
end

function OpenAPI.validate_property(::Type{ CreateFineTuningJobRequestHyperparameters }, name::Symbol, val)
end
