# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""CreateChatCompletionFunctionResponse
Represents a chat completion response returned by model, based on the provided input.

    CreateChatCompletionFunctionResponse(;
        id=nothing,
        choices=nothing,
        created=nothing,
        model=nothing,
        system_fingerprint=nothing,
        object=nothing,
        usage=nothing,
    )

    - id::String : A unique identifier for the chat completion.
    - choices::Vector{CreateChatCompletionFunctionResponseChoicesInner} : A list of chat completion choices. Can be more than one if &#x60;n&#x60; is greater than 1.
    - created::Int64 : The Unix timestamp (in seconds) of when the chat completion was created.
    - model::String : The model used for the chat completion.
    - system_fingerprint::String : This fingerprint represents the backend configuration that the model runs with.  Can be used in conjunction with the &#x60;seed&#x60; request parameter to understand when backend changes have been made that might impact determinism. 
    - object::String : The object type, which is always &#x60;chat.completion&#x60;.
    - usage::CompletionUsage
"""
Base.@kwdef mutable struct CreateChatCompletionFunctionResponse <: OpenAPI.APIModel
    id::Union{Nothing, String} = nothing
    choices::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{CreateChatCompletionFunctionResponseChoicesInner} }
    created::Union{Nothing, Int64} = nothing
    model::Union{Nothing, String} = nothing
    system_fingerprint::Union{Nothing, String} = nothing
    object::Union{Nothing, String} = nothing
    usage = nothing # spec type: Union{ Nothing, CompletionUsage }

    function CreateChatCompletionFunctionResponse(id, choices, created, model, system_fingerprint, object, usage, )
        OpenAPI.validate_property(CreateChatCompletionFunctionResponse, Symbol("id"), id)
        OpenAPI.validate_property(CreateChatCompletionFunctionResponse, Symbol("choices"), choices)
        OpenAPI.validate_property(CreateChatCompletionFunctionResponse, Symbol("created"), created)
        OpenAPI.validate_property(CreateChatCompletionFunctionResponse, Symbol("model"), model)
        OpenAPI.validate_property(CreateChatCompletionFunctionResponse, Symbol("system_fingerprint"), system_fingerprint)
        OpenAPI.validate_property(CreateChatCompletionFunctionResponse, Symbol("object"), object)
        OpenAPI.validate_property(CreateChatCompletionFunctionResponse, Symbol("usage"), usage)
        return new(id, choices, created, model, system_fingerprint, object, usage, )
    end
end # type CreateChatCompletionFunctionResponse

const _property_types_CreateChatCompletionFunctionResponse = Dict{Symbol,String}(Symbol("id")=>"String", Symbol("choices")=>"Vector{CreateChatCompletionFunctionResponseChoicesInner}", Symbol("created")=>"Int64", Symbol("model")=>"String", Symbol("system_fingerprint")=>"String", Symbol("object")=>"String", Symbol("usage")=>"CompletionUsage", )
OpenAPI.property_type(::Type{ CreateChatCompletionFunctionResponse }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_CreateChatCompletionFunctionResponse[name]))}

function check_required(o::CreateChatCompletionFunctionResponse)
    o.id === nothing && (return false)
    o.choices === nothing && (return false)
    o.created === nothing && (return false)
    o.model === nothing && (return false)
    o.object === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ CreateChatCompletionFunctionResponse }, name::Symbol, val)
    if name === Symbol("object")
        OpenAPI.validate_param(name, "CreateChatCompletionFunctionResponse", :enum, val, ["chat.completion"])
    end
end
