# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.



@doc raw"""CreateImageEditRequest_model
The model to use for image generation. Only &#x60;dall-e-2&#x60; is supported at this time.

    CreateImageEditRequestModel(; value=nothing)
"""
mutable struct CreateImageEditRequestModel <: OpenAPI.AnyOfAPIModel
    value::Any # Union{ String }
    CreateImageEditRequestModel() = new()
    CreateImageEditRequestModel(value) = new(value)
end # type CreateImageEditRequestModel

function OpenAPI.property_type(::Type{ CreateImageEditRequestModel }, name::Symbol, json::Dict{String,Any})
    
    # no discriminator specified, can't determine the exact type
    return fieldtype(CreateImageEditRequestModel, name)
end
