# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""CreateTranscriptionResponse

    CreateTranscriptionResponse(;
        text=nothing,
    )

    - text::String
"""
Base.@kwdef mutable struct CreateTranscriptionResponse <: OpenAPI.APIModel
    text::Union{Nothing, String} = nothing

    function CreateTranscriptionResponse(text, )
        OpenAPI.validate_property(CreateTranscriptionResponse, Symbol("text"), text)
        return new(text, )
    end
end # type CreateTranscriptionResponse

const _property_types_CreateTranscriptionResponse = Dict{Symbol,String}(Symbol("text")=>"String", )
OpenAPI.property_type(::Type{ CreateTranscriptionResponse }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_CreateTranscriptionResponse[name]))}

function check_required(o::CreateTranscriptionResponse)
    o.text === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ CreateTranscriptionResponse }, name::Symbol, val)
end
