# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.



@doc raw"""ChatCompletionRequestMessage

    ChatCompletionRequestMessage(; value=nothing)
"""
mutable struct ChatCompletionRequestMessage <: OpenAPI.OneOfAPIModel
    value::Any # Union{ ChatCompletionRequestAssistantMessage, ChatCompletionRequestFunctionMessage, ChatCompletionRequestSystemMessage, ChatCompletionRequestToolMessage, ChatCompletionRequestUserMessage }
    ChatCompletionRequestMessage() = new()
    ChatCompletionRequestMessage(value) = new(value)
end # type ChatCompletionRequestMessage

function OpenAPI.property_type(::Type{ ChatCompletionRequestMessage }, name::Symbol, json::Dict{String,Any})
    
    # no discriminator specified, can't determine the exact type
    return fieldtype(ChatCompletionRequestMessage, name)
end
