# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""ChatCompletionNamedToolChoice_function

    ChatCompletionNamedToolChoiceFunction(;
        name=nothing,
    )

    - name::String : The name of the function to call.
"""
Base.@kwdef mutable struct ChatCompletionNamedToolChoiceFunction <: OpenAPI.APIModel
    name::Union{Nothing, String} = nothing

    function ChatCompletionNamedToolChoiceFunction(name, )
        OpenAPI.validate_property(ChatCompletionNamedToolChoiceFunction, Symbol("name"), name)
        return new(name, )
    end
end # type ChatCompletionNamedToolChoiceFunction

const _property_types_ChatCompletionNamedToolChoiceFunction = Dict{Symbol,String}(Symbol("name")=>"String", )
OpenAPI.property_type(::Type{ ChatCompletionNamedToolChoiceFunction }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ChatCompletionNamedToolChoiceFunction[name]))}

function check_required(o::ChatCompletionNamedToolChoiceFunction)
    o.name === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ ChatCompletionNamedToolChoiceFunction }, name::Symbol, val)
end
