# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""CreateTranslationResponse

    CreateTranslationResponse(;
        text=nothing,
    )

    - text::String
"""
Base.@kwdef mutable struct CreateTranslationResponse <: OpenAPI.APIModel
    text::Union{Nothing, String} = nothing

    function CreateTranslationResponse(text, )
        OpenAPI.validate_property(CreateTranslationResponse, Symbol("text"), text)
        return new(text, )
    end
end # type CreateTranslationResponse

const _property_types_CreateTranslationResponse = Dict{Symbol,String}(Symbol("text")=>"String", )
OpenAPI.property_type(::Type{ CreateTranslationResponse }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_CreateTranslationResponse[name]))}

function check_required(o::CreateTranslationResponse)
    o.text === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ CreateTranslationResponse }, name::Symbol, val)
end
