# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""CreateModerationResponse_results_inner_category_scores
A list of the categories along with their scores as predicted by model.

    CreateModerationResponseResultsInnerCategoryScores(;
        hate=nothing,
        var"hate/threatening"=nothing,
        harassment=nothing,
        var"harassment/threatening"=nothing,
        var"self-harm"=nothing,
        var"self-harm/intent"=nothing,
        var"self-harm/instructions"=nothing,
        sexual=nothing,
        var"sexual/minors"=nothing,
        violence=nothing,
        var"violence/graphic"=nothing,
    )

    - hate::Float64 : The score for the category &#39;hate&#39;.
    - var"hate/threatening"::Float64 : The score for the category &#39;hate/threatening&#39;.
    - harassment::Float64 : The score for the category &#39;harassment&#39;.
    - var"harassment/threatening"::Float64 : The score for the category &#39;harassment/threatening&#39;.
    - var"self-harm"::Float64 : The score for the category &#39;self-harm&#39;.
    - var"self-harm/intent"::Float64 : The score for the category &#39;self-harm/intent&#39;.
    - var"self-harm/instructions"::Float64 : The score for the category &#39;self-harm/instructions&#39;.
    - sexual::Float64 : The score for the category &#39;sexual&#39;.
    - var"sexual/minors"::Float64 : The score for the category &#39;sexual/minors&#39;.
    - violence::Float64 : The score for the category &#39;violence&#39;.
    - var"violence/graphic"::Float64 : The score for the category &#39;violence/graphic&#39;.
"""
Base.@kwdef mutable struct CreateModerationResponseResultsInnerCategoryScores <: OpenAPI.APIModel
    hate::Union{Nothing, Float64} = nothing
    var"hate/threatening"::Union{Nothing, Float64} = nothing
    harassment::Union{Nothing, Float64} = nothing
    var"harassment/threatening"::Union{Nothing, Float64} = nothing
    var"self-harm"::Union{Nothing, Float64} = nothing
    var"self-harm/intent"::Union{Nothing, Float64} = nothing
    var"self-harm/instructions"::Union{Nothing, Float64} = nothing
    sexual::Union{Nothing, Float64} = nothing
    var"sexual/minors"::Union{Nothing, Float64} = nothing
    violence::Union{Nothing, Float64} = nothing
    var"violence/graphic"::Union{Nothing, Float64} = nothing

    function CreateModerationResponseResultsInnerCategoryScores(hate, var"hate/threatening", harassment, var"harassment/threatening", var"self-harm", var"self-harm/intent", var"self-harm/instructions", sexual, var"sexual/minors", violence, var"violence/graphic", )
        OpenAPI.validate_property(CreateModerationResponseResultsInnerCategoryScores, Symbol("hate"), hate)
        OpenAPI.validate_property(CreateModerationResponseResultsInnerCategoryScores, Symbol("hate/threatening"), var"hate/threatening")
        OpenAPI.validate_property(CreateModerationResponseResultsInnerCategoryScores, Symbol("harassment"), harassment)
        OpenAPI.validate_property(CreateModerationResponseResultsInnerCategoryScores, Symbol("harassment/threatening"), var"harassment/threatening")
        OpenAPI.validate_property(CreateModerationResponseResultsInnerCategoryScores, Symbol("self-harm"), var"self-harm")
        OpenAPI.validate_property(CreateModerationResponseResultsInnerCategoryScores, Symbol("self-harm/intent"), var"self-harm/intent")
        OpenAPI.validate_property(CreateModerationResponseResultsInnerCategoryScores, Symbol("self-harm/instructions"), var"self-harm/instructions")
        OpenAPI.validate_property(CreateModerationResponseResultsInnerCategoryScores, Symbol("sexual"), sexual)
        OpenAPI.validate_property(CreateModerationResponseResultsInnerCategoryScores, Symbol("sexual/minors"), var"sexual/minors")
        OpenAPI.validate_property(CreateModerationResponseResultsInnerCategoryScores, Symbol("violence"), violence)
        OpenAPI.validate_property(CreateModerationResponseResultsInnerCategoryScores, Symbol("violence/graphic"), var"violence/graphic")
        return new(hate, var"hate/threatening", harassment, var"harassment/threatening", var"self-harm", var"self-harm/intent", var"self-harm/instructions", sexual, var"sexual/minors", violence, var"violence/graphic", )
    end
end # type CreateModerationResponseResultsInnerCategoryScores

const _property_types_CreateModerationResponseResultsInnerCategoryScores = Dict{Symbol,String}(Symbol("hate")=>"Float64", Symbol("hate/threatening")=>"Float64", Symbol("harassment")=>"Float64", Symbol("harassment/threatening")=>"Float64", Symbol("self-harm")=>"Float64", Symbol("self-harm/intent")=>"Float64", Symbol("self-harm/instructions")=>"Float64", Symbol("sexual")=>"Float64", Symbol("sexual/minors")=>"Float64", Symbol("violence")=>"Float64", Symbol("violence/graphic")=>"Float64", )
OpenAPI.property_type(::Type{ CreateModerationResponseResultsInnerCategoryScores }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_CreateModerationResponseResultsInnerCategoryScores[name]))}

function check_required(o::CreateModerationResponseResultsInnerCategoryScores)
    o.hate === nothing && (return false)
    o.var"hate/threatening" === nothing && (return false)
    o.harassment === nothing && (return false)
    o.var"harassment/threatening" === nothing && (return false)
    o.var"self-harm" === nothing && (return false)
    o.var"self-harm/intent" === nothing && (return false)
    o.var"self-harm/instructions" === nothing && (return false)
    o.sexual === nothing && (return false)
    o.var"sexual/minors" === nothing && (return false)
    o.violence === nothing && (return false)
    o.var"violence/graphic" === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ CreateModerationResponseResultsInnerCategoryScores }, name::Symbol, val)
end
