# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""ChatCompletionTool

    ChatCompletionTool(;
        type=nothing,
        var"function"=nothing,
    )

    - type::String : The type of the tool. Currently, only &#x60;function&#x60; is supported.
    - var"function"::FunctionObject
"""
Base.@kwdef mutable struct ChatCompletionTool <: OpenAPI.APIModel
    type::Union{Nothing, String} = nothing
    var"function" = nothing # spec type: Union{ Nothing, FunctionObject }

    function ChatCompletionTool(type, var"function", )
        OpenAPI.validate_property(ChatCompletionTool, Symbol("type"), type)
        OpenAPI.validate_property(ChatCompletionTool, Symbol("function"), var"function")
        return new(type, var"function", )
    end
end # type ChatCompletionTool

const _property_types_ChatCompletionTool = Dict{Symbol,String}(Symbol("type")=>"String", Symbol("function")=>"FunctionObject", )
OpenAPI.property_type(::Type{ ChatCompletionTool }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ChatCompletionTool[name]))}

function check_required(o::ChatCompletionTool)
    o.type === nothing && (return false)
    o.var"function" === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ ChatCompletionTool }, name::Symbol, val)
    if name === Symbol("type")
        OpenAPI.validate_param(name, "ChatCompletionTool", :enum, val, ["function"])
    end
end
