# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""AssistantToolsCode

    AssistantToolsCode(;
        type=nothing,
    )

    - type::String : The type of tool being defined: &#x60;code_interpreter&#x60;
"""
Base.@kwdef mutable struct AssistantToolsCode <: OpenAPI.APIModel
    type::Union{Nothing, String} = nothing

    function AssistantToolsCode(type, )
        OpenAPI.validate_property(AssistantToolsCode, Symbol("type"), type)
        return new(type, )
    end
end # type AssistantToolsCode

const _property_types_AssistantToolsCode = Dict{Symbol,String}(Symbol("type")=>"String", )
OpenAPI.property_type(::Type{ AssistantToolsCode }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_AssistantToolsCode[name]))}

function check_required(o::AssistantToolsCode)
    o.type === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ AssistantToolsCode }, name::Symbol, val)
    if name === Symbol("type")
        OpenAPI.validate_param(name, "AssistantToolsCode", :enum, val, ["code_interpreter"])
    end
end
