# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""CreateEditResponse_choices_inner

    CreateEditResponseChoicesInner(;
        finish_reason=nothing,
        index=nothing,
        text=nothing,
    )

    - finish_reason::String : The reason the model stopped generating tokens. This will be &#x60;stop&#x60; if the model hit a natural stop point or a provided stop sequence, &#x60;length&#x60; if the maximum number of tokens specified in the request was reached, or &#x60;content_filter&#x60; if content was omitted due to a flag from our content filters. 
    - index::Int64 : The index of the choice in the list of choices.
    - text::String : The edited result.
"""
Base.@kwdef mutable struct CreateEditResponseChoicesInner <: OpenAPI.APIModel
    finish_reason::Union{Nothing, String} = nothing
    index::Union{Nothing, Int64} = nothing
    text::Union{Nothing, String} = nothing

    function CreateEditResponseChoicesInner(finish_reason, index, text, )
        OpenAPI.validate_property(CreateEditResponseChoicesInner, Symbol("finish_reason"), finish_reason)
        OpenAPI.validate_property(CreateEditResponseChoicesInner, Symbol("index"), index)
        OpenAPI.validate_property(CreateEditResponseChoicesInner, Symbol("text"), text)
        return new(finish_reason, index, text, )
    end
end # type CreateEditResponseChoicesInner

const _property_types_CreateEditResponseChoicesInner = Dict{Symbol,String}(Symbol("finish_reason")=>"String", Symbol("index")=>"Int64", Symbol("text")=>"String", )
OpenAPI.property_type(::Type{ CreateEditResponseChoicesInner }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_CreateEditResponseChoicesInner[name]))}

function check_required(o::CreateEditResponseChoicesInner)
    o.finish_reason === nothing && (return false)
    o.index === nothing && (return false)
    o.text === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ CreateEditResponseChoicesInner }, name::Symbol, val)
    if name === Symbol("finish_reason")
        OpenAPI.validate_param(name, "CreateEditResponseChoicesInner", :enum, val, ["stop", "length"])
    end
end
