# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.



@doc raw"""CreateThreadAndRunRequest_tools_inner

    CreateThreadAndRunRequestToolsInner(; value=nothing)
"""
mutable struct CreateThreadAndRunRequestToolsInner <: OpenAPI.OneOfAPIModel
    value::Any # Union{ AssistantToolsCode, AssistantToolsFunction, AssistantToolsRetrieval }
    CreateThreadAndRunRequestToolsInner() = new()
    CreateThreadAndRunRequestToolsInner(value) = new(value)
end # type CreateThreadAndRunRequestToolsInner

function OpenAPI.property_type(::Type{ CreateThreadAndRunRequestToolsInner }, name::Symbol, json::Dict{String,Any})
    
    # no discriminator specified, can't determine the exact type
    return fieldtype(CreateThreadAndRunRequestToolsInner, name)
end
