# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""CreateChatCompletionRequest_response_format
An object specifying the format that the model must output.   Setting to &#x60;{ \&quot;type\&quot;: \&quot;json_object\&quot; }&#x60; enables JSON mode, which guarantees the message the model generates is valid JSON.  **Important:** when using JSON mode, you **must** also instruct the model to produce JSON yourself via a system or user message. Without this, the model may generate an unending stream of whitespace until the generation reaches the token limit, resulting in a long-running and seemingly \&quot;stuck\&quot; request. Also note that the message content may be partially cut off if &#x60;finish_reason&#x3D;\&quot;length\&quot;&#x60;, which indicates the generation exceeded &#x60;max_tokens&#x60; or the conversation exceeded the max context length. 

    CreateChatCompletionRequestResponseFormat(;
        type="text",
    )

    - type::String : Must be one of &#x60;text&#x60; or &#x60;json_object&#x60;.
"""
Base.@kwdef mutable struct CreateChatCompletionRequestResponseFormat <: OpenAPI.APIModel
    type::Union{Nothing, String} = "text"

    function CreateChatCompletionRequestResponseFormat(type, )
        OpenAPI.validate_property(CreateChatCompletionRequestResponseFormat, Symbol("type"), type)
        return new(type, )
    end
end # type CreateChatCompletionRequestResponseFormat

const _property_types_CreateChatCompletionRequestResponseFormat = Dict{Symbol,String}(Symbol("type")=>"String", )
OpenAPI.property_type(::Type{ CreateChatCompletionRequestResponseFormat }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_CreateChatCompletionRequestResponseFormat[name]))}

function check_required(o::CreateChatCompletionRequestResponseFormat)
    true
end

function OpenAPI.validate_property(::Type{ CreateChatCompletionRequestResponseFormat }, name::Symbol, val)
    if name === Symbol("type")
        OpenAPI.validate_param(name, "CreateChatCompletionRequestResponseFormat", :enum, val, ["text", "json_object"])
    end
end
