# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""DeleteMessageResponse

    DeleteMessageResponse(;
        id=nothing,
        deleted=nothing,
        object=nothing,
    )

    - id::String
    - deleted::Bool
    - object::String
"""
Base.@kwdef mutable struct DeleteMessageResponse <: OpenAPI.APIModel
    id::Union{Nothing, String} = nothing
    deleted::Union{Nothing, Bool} = nothing
    object::Union{Nothing, String} = nothing

    function DeleteMessageResponse(id, deleted, object, )
        OpenAPI.validate_property(DeleteMessageResponse, Symbol("id"), id)
        OpenAPI.validate_property(DeleteMessageResponse, Symbol("deleted"), deleted)
        OpenAPI.validate_property(DeleteMessageResponse, Symbol("object"), object)
        return new(id, deleted, object, )
    end
end # type DeleteMessageResponse

const _property_types_DeleteMessageResponse = Dict{Symbol,String}(Symbol("id")=>"String", Symbol("deleted")=>"Bool", Symbol("object")=>"String", )
OpenAPI.property_type(::Type{ DeleteMessageResponse }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_DeleteMessageResponse[name]))}

function check_required(o::DeleteMessageResponse)
    o.id === nothing && (return false)
    o.deleted === nothing && (return false)
    o.object === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ DeleteMessageResponse }, name::Symbol, val)
    if name === Symbol("object")
        OpenAPI.validate_param(name, "DeleteMessageResponse", :enum, val, ["thread.message.deleted"])
    end
end
