# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.



@doc raw"""ChatCompletionToolChoiceOption
Controls which (if any) function is called by the model. &#x60;none&#x60; means the model will not call a function and instead generates a message. &#x60;auto&#x60; means the model can pick between generating a message or calling a function. Specifying a particular function via &#x60;{\&quot;type: \&quot;function\&quot;, \&quot;function\&quot;: {\&quot;name\&quot;: \&quot;my_function\&quot;}}&#x60; forces the model to call that function.  &#x60;none&#x60; is the default when no functions are present. &#x60;auto&#x60; is the default if functions are present. 

    ChatCompletionToolChoiceOption(; value=nothing)
"""
mutable struct ChatCompletionToolChoiceOption <: OpenAPI.OneOfAPIModel
    value::Any # Union{ ChatCompletionNamedToolChoice, String }
    ChatCompletionToolChoiceOption() = new()
    ChatCompletionToolChoiceOption(value) = new(value)
end # type ChatCompletionToolChoiceOption

function OpenAPI.property_type(::Type{ ChatCompletionToolChoiceOption }, name::Symbol, json::Dict{String,Any})
    
    # no discriminator specified, can't determine the exact type
    return fieldtype(ChatCompletionToolChoiceOption, name)
end
