# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""RunStepObject_last_error
The last error associated with this run step. Will be &#x60;null&#x60; if there are no errors.

    RunStepObjectLastError(;
        code=nothing,
        message=nothing,
    )

    - code::String : One of &#x60;server_error&#x60; or &#x60;rate_limit_exceeded&#x60;.
    - message::String : A human-readable description of the error.
"""
Base.@kwdef mutable struct RunStepObjectLastError <: OpenAPI.APIModel
    code::Union{Nothing, String} = nothing
    message::Union{Nothing, String} = nothing

    function RunStepObjectLastError(code, message, )
        OpenAPI.validate_property(RunStepObjectLastError, Symbol("code"), code)
        OpenAPI.validate_property(RunStepObjectLastError, Symbol("message"), message)
        return new(code, message, )
    end
end # type RunStepObjectLastError

const _property_types_RunStepObjectLastError = Dict{Symbol,String}(Symbol("code")=>"String", Symbol("message")=>"String", )
OpenAPI.property_type(::Type{ RunStepObjectLastError }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_RunStepObjectLastError[name]))}

function check_required(o::RunStepObjectLastError)
    o.code === nothing && (return false)
    o.message === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ RunStepObjectLastError }, name::Symbol, val)
    if name === Symbol("code")
        OpenAPI.validate_param(name, "RunStepObjectLastError", :enum, val, ["server_error", "rate_limit_exceeded"])
    end
end
