# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.



@doc raw"""CreateCompletionRequest_stop
Up to 4 sequences where the API will stop generating further tokens. The returned text will not contain the stop sequence. 

    CreateCompletionRequestStop(; value=nothing)
"""
mutable struct CreateCompletionRequestStop <: OpenAPI.OneOfAPIModel
    value::Any # Union{ String, Vector{String} }
    CreateCompletionRequestStop() = new()
    CreateCompletionRequestStop(value) = new(value)
end # type CreateCompletionRequestStop

function OpenAPI.property_type(::Type{ CreateCompletionRequestStop }, name::Symbol, json::Dict{String,Any})
    
    # no discriminator specified, can't determine the exact type
    return fieldtype(CreateCompletionRequestStop, name)
end
