# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""CreateFineTuneRequest_hyperparameters
The hyperparameters used for the fine-tuning job.

    CreateFineTuneRequestHyperparameters(;
        n_epochs=nothing,
    )

    - n_epochs::CreateFineTuneRequestHyperparametersNEpochs
"""
Base.@kwdef mutable struct CreateFineTuneRequestHyperparameters <: OpenAPI.APIModel
    n_epochs = nothing # spec type: Union{ Nothing, CreateFineTuneRequestHyperparametersNEpochs }

    function CreateFineTuneRequestHyperparameters(n_epochs, )
        OpenAPI.validate_property(CreateFineTuneRequestHyperparameters, Symbol("n_epochs"), n_epochs)
        return new(n_epochs, )
    end
end # type CreateFineTuneRequestHyperparameters

const _property_types_CreateFineTuneRequestHyperparameters = Dict{Symbol,String}(Symbol("n_epochs")=>"CreateFineTuneRequestHyperparametersNEpochs", )
OpenAPI.property_type(::Type{ CreateFineTuneRequestHyperparameters }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_CreateFineTuneRequestHyperparameters[name]))}

function check_required(o::CreateFineTuneRequestHyperparameters)
    true
end

function OpenAPI.validate_property(::Type{ CreateFineTuneRequestHyperparameters }, name::Symbol, val)
end
