# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.



@doc raw"""CreateFineTuneRequest_hyperparameters_n_epochs
The number of epochs to train the model for. An epoch refers to one full cycle through the training dataset. 

    CreateFineTuneRequestHyperparametersNEpochs(; value=nothing)
"""
mutable struct CreateFineTuneRequestHyperparametersNEpochs <: OpenAPI.OneOfAPIModel
    value::Any # Union{ Int64, String }
    CreateFineTuneRequestHyperparametersNEpochs() = new()
    CreateFineTuneRequestHyperparametersNEpochs(value) = new(value)
end # type CreateFineTuneRequestHyperparametersNEpochs

function OpenAPI.property_type(::Type{ CreateFineTuneRequestHyperparametersNEpochs }, name::Symbol, json::Dict{String,Any})
    
    # no discriminator specified, can't determine the exact type
    return fieldtype(CreateFineTuneRequestHyperparametersNEpochs, name)
end
