# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""MessageContentImageFileObject_image_file

    MessageContentImageFileObjectImageFile(;
        file_id=nothing,
    )

    - file_id::String : The [File](/docs/api-reference/files) ID of the image in the message content.
"""
Base.@kwdef mutable struct MessageContentImageFileObjectImageFile <: OpenAPI.APIModel
    file_id::Union{Nothing, String} = nothing

    function MessageContentImageFileObjectImageFile(file_id, )
        OpenAPI.validate_property(MessageContentImageFileObjectImageFile, Symbol("file_id"), file_id)
        return new(file_id, )
    end
end # type MessageContentImageFileObjectImageFile

const _property_types_MessageContentImageFileObjectImageFile = Dict{Symbol,String}(Symbol("file_id")=>"String", )
OpenAPI.property_type(::Type{ MessageContentImageFileObjectImageFile }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_MessageContentImageFileObjectImageFile[name]))}

function check_required(o::MessageContentImageFileObjectImageFile)
    o.file_id === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ MessageContentImageFileObjectImageFile }, name::Symbol, val)
end
