# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""RunObject_required_action_submit_tool_outputs
Details on the tool outputs needed for this run to continue.

    RunObjectRequiredActionSubmitToolOutputs(;
        tool_calls=nothing,
    )

    - tool_calls::Vector{RunToolCallObject} : A list of the relevant tool calls.
"""
Base.@kwdef mutable struct RunObjectRequiredActionSubmitToolOutputs <: OpenAPI.APIModel
    tool_calls::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{RunToolCallObject} }

    function RunObjectRequiredActionSubmitToolOutputs(tool_calls, )
        OpenAPI.validate_property(RunObjectRequiredActionSubmitToolOutputs, Symbol("tool_calls"), tool_calls)
        return new(tool_calls, )
    end
end # type RunObjectRequiredActionSubmitToolOutputs

const _property_types_RunObjectRequiredActionSubmitToolOutputs = Dict{Symbol,String}(Symbol("tool_calls")=>"Vector{RunToolCallObject}", )
OpenAPI.property_type(::Type{ RunObjectRequiredActionSubmitToolOutputs }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_RunObjectRequiredActionSubmitToolOutputs[name]))}

function check_required(o::RunObjectRequiredActionSubmitToolOutputs)
    o.tool_calls === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ RunObjectRequiredActionSubmitToolOutputs }, name::Symbol, val)
end
