# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""ListMessageFilesResponse

    ListMessageFilesResponse(;
        object=nothing,
        data=nothing,
        first_id=nothing,
        last_id=nothing,
        has_more=nothing,
    )

    - object::String
    - data::Vector{MessageFileObject}
    - first_id::String
    - last_id::String
    - has_more::Bool
"""
Base.@kwdef mutable struct ListMessageFilesResponse <: OpenAPI.APIModel
    object::Union{Nothing, String} = nothing
    data::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{MessageFileObject} }
    first_id::Union{Nothing, String} = nothing
    last_id::Union{Nothing, String} = nothing
    has_more::Union{Nothing, Bool} = nothing

    function ListMessageFilesResponse(object, data, first_id, last_id, has_more, )
        OpenAPI.validate_property(ListMessageFilesResponse, Symbol("object"), object)
        OpenAPI.validate_property(ListMessageFilesResponse, Symbol("data"), data)
        OpenAPI.validate_property(ListMessageFilesResponse, Symbol("first_id"), first_id)
        OpenAPI.validate_property(ListMessageFilesResponse, Symbol("last_id"), last_id)
        OpenAPI.validate_property(ListMessageFilesResponse, Symbol("has_more"), has_more)
        return new(object, data, first_id, last_id, has_more, )
    end
end # type ListMessageFilesResponse

const _property_types_ListMessageFilesResponse = Dict{Symbol,String}(Symbol("object")=>"String", Symbol("data")=>"Vector{MessageFileObject}", Symbol("first_id")=>"String", Symbol("last_id")=>"String", Symbol("has_more")=>"Bool", )
OpenAPI.property_type(::Type{ ListMessageFilesResponse }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ListMessageFilesResponse[name]))}

function check_required(o::ListMessageFilesResponse)
    o.object === nothing && (return false)
    o.data === nothing && (return false)
    o.first_id === nothing && (return false)
    o.last_id === nothing && (return false)
    o.has_more === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ ListMessageFilesResponse }, name::Symbol, val)
end
