# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""ChatCompletionRequestSystemMessage

    ChatCompletionRequestSystemMessage(;
        content=nothing,
        role=nothing,
        name=nothing,
    )

    - content::String : The contents of the system message.
    - role::String : The role of the messages author, in this case &#x60;system&#x60;.
    - name::String : An optional name for the participant. Provides the model information to differentiate between participants of the same role.
"""
Base.@kwdef mutable struct ChatCompletionRequestSystemMessage <: OpenAPI.APIModel
    content::Union{Nothing, String} = nothing
    role::Union{Nothing, String} = nothing
    name::Union{Nothing, String} = nothing

    function ChatCompletionRequestSystemMessage(content, role, name, )
        OpenAPI.validate_property(ChatCompletionRequestSystemMessage, Symbol("content"), content)
        OpenAPI.validate_property(ChatCompletionRequestSystemMessage, Symbol("role"), role)
        OpenAPI.validate_property(ChatCompletionRequestSystemMessage, Symbol("name"), name)
        return new(content, role, name, )
    end
end # type ChatCompletionRequestSystemMessage

const _property_types_ChatCompletionRequestSystemMessage = Dict{Symbol,String}(Symbol("content")=>"String", Symbol("role")=>"String", Symbol("name")=>"String", )
OpenAPI.property_type(::Type{ ChatCompletionRequestSystemMessage }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ChatCompletionRequestSystemMessage[name]))}

function check_required(o::ChatCompletionRequestSystemMessage)
    o.content === nothing && (return false)
    o.role === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ ChatCompletionRequestSystemMessage }, name::Symbol, val)
    if name === Symbol("role")
        OpenAPI.validate_param(name, "ChatCompletionRequestSystemMessage", :enum, val, ["system"])
    end
end
