# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""FineTuningJob_hyperparameters
The hyperparameters used for the fine-tuning job. See the [fine-tuning guide](/docs/guides/fine-tuning) for more details.

    FineTuningJobHyperparameters(;
        n_epochs=nothing,
    )

    - n_epochs::FineTuningJobHyperparametersNEpochs
"""
Base.@kwdef mutable struct FineTuningJobHyperparameters <: OpenAPI.APIModel
    n_epochs = nothing # spec type: Union{ Nothing, FineTuningJobHyperparametersNEpochs }

    function FineTuningJobHyperparameters(n_epochs, )
        OpenAPI.validate_property(FineTuningJobHyperparameters, Symbol("n_epochs"), n_epochs)
        return new(n_epochs, )
    end
end # type FineTuningJobHyperparameters

const _property_types_FineTuningJobHyperparameters = Dict{Symbol,String}(Symbol("n_epochs")=>"FineTuningJobHyperparametersNEpochs", )
OpenAPI.property_type(::Type{ FineTuningJobHyperparameters }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_FineTuningJobHyperparameters[name]))}

function check_required(o::FineTuningJobHyperparameters)
    o.n_epochs === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ FineTuningJobHyperparameters }, name::Symbol, val)
end
