# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""SubmitToolOutputsRunRequest

    SubmitToolOutputsRunRequest(;
        tool_outputs=nothing,
    )

    - tool_outputs::Vector{SubmitToolOutputsRunRequestToolOutputsInner} : A list of tools for which the outputs are being submitted.
"""
Base.@kwdef mutable struct SubmitToolOutputsRunRequest <: OpenAPI.APIModel
    tool_outputs::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{SubmitToolOutputsRunRequestToolOutputsInner} }

    function SubmitToolOutputsRunRequest(tool_outputs, )
        OpenAPI.validate_property(SubmitToolOutputsRunRequest, Symbol("tool_outputs"), tool_outputs)
        return new(tool_outputs, )
    end
end # type SubmitToolOutputsRunRequest

const _property_types_SubmitToolOutputsRunRequest = Dict{Symbol,String}(Symbol("tool_outputs")=>"Vector{SubmitToolOutputsRunRequestToolOutputsInner}", )
OpenAPI.property_type(::Type{ SubmitToolOutputsRunRequest }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_SubmitToolOutputsRunRequest[name]))}

function check_required(o::SubmitToolOutputsRunRequest)
    o.tool_outputs === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ SubmitToolOutputsRunRequest }, name::Symbol, val)
end
