# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.



@doc raw"""CreateModerationRequest_input
The input text to classify

    CreateModerationRequestInput(; value=nothing)
"""
mutable struct CreateModerationRequestInput <: OpenAPI.OneOfAPIModel
    value::Any # Union{ String, Vector{String} }
    CreateModerationRequestInput() = new()
    CreateModerationRequestInput(value) = new(value)
end # type CreateModerationRequestInput

function OpenAPI.property_type(::Type{ CreateModerationRequestInput }, name::Symbol, json::Dict{String,Any})
    
    # no discriminator specified, can't determine the exact type
    return fieldtype(CreateModerationRequestInput, name)
end
