# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""ListFineTuneEventsResponse

    ListFineTuneEventsResponse(;
        data=nothing,
        object=nothing,
    )

    - data::Vector{FineTuneEvent}
    - object::String
"""
Base.@kwdef mutable struct ListFineTuneEventsResponse <: OpenAPI.APIModel
    data::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{FineTuneEvent} }
    object::Union{Nothing, String} = nothing

    function ListFineTuneEventsResponse(data, object, )
        OpenAPI.validate_property(ListFineTuneEventsResponse, Symbol("data"), data)
        OpenAPI.validate_property(ListFineTuneEventsResponse, Symbol("object"), object)
        return new(data, object, )
    end
end # type ListFineTuneEventsResponse

const _property_types_ListFineTuneEventsResponse = Dict{Symbol,String}(Symbol("data")=>"Vector{FineTuneEvent}", Symbol("object")=>"String", )
OpenAPI.property_type(::Type{ ListFineTuneEventsResponse }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ListFineTuneEventsResponse[name]))}

function check_required(o::ListFineTuneEventsResponse)
    o.data === nothing && (return false)
    o.object === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ ListFineTuneEventsResponse }, name::Symbol, val)
    if name === Symbol("object")
        OpenAPI.validate_param(name, "ListFineTuneEventsResponse", :enum, val, ["list"])
    end
end
