# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""AssistantFileObject
A list of [Files](/docs/api-reference/files) attached to an &#x60;assistant&#x60;.

    AssistantFileObject(;
        id=nothing,
        object=nothing,
        created_at=nothing,
        assistant_id=nothing,
    )

    - id::String : The identifier, which can be referenced in API endpoints.
    - object::String : The object type, which is always &#x60;assistant.file&#x60;.
    - created_at::Int64 : The Unix timestamp (in seconds) for when the assistant file was created.
    - assistant_id::String : The assistant ID that the file is attached to.
"""
Base.@kwdef mutable struct AssistantFileObject <: OpenAPI.APIModel
    id::Union{Nothing, String} = nothing
    object::Union{Nothing, String} = nothing
    created_at::Union{Nothing, Int64} = nothing
    assistant_id::Union{Nothing, String} = nothing

    function AssistantFileObject(id, object, created_at, assistant_id, )
        OpenAPI.validate_property(AssistantFileObject, Symbol("id"), id)
        OpenAPI.validate_property(AssistantFileObject, Symbol("object"), object)
        OpenAPI.validate_property(AssistantFileObject, Symbol("created_at"), created_at)
        OpenAPI.validate_property(AssistantFileObject, Symbol("assistant_id"), assistant_id)
        return new(id, object, created_at, assistant_id, )
    end
end # type AssistantFileObject

const _property_types_AssistantFileObject = Dict{Symbol,String}(Symbol("id")=>"String", Symbol("object")=>"String", Symbol("created_at")=>"Int64", Symbol("assistant_id")=>"String", )
OpenAPI.property_type(::Type{ AssistantFileObject }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_AssistantFileObject[name]))}

function check_required(o::AssistantFileObject)
    o.id === nothing && (return false)
    o.object === nothing && (return false)
    o.created_at === nothing && (return false)
    o.assistant_id === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ AssistantFileObject }, name::Symbol, val)
    if name === Symbol("object")
        OpenAPI.validate_param(name, "AssistantFileObject", :enum, val, ["assistant.file"])
    end
end
