# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""ListFilesResponse

    ListFilesResponse(;
        data=nothing,
        object=nothing,
    )

    - data::Vector{OpenAIFile}
    - object::String
"""
Base.@kwdef mutable struct ListFilesResponse <: OpenAPI.APIModel
    data::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{OpenAIFile} }
    object::Union{Nothing, String} = nothing

    function ListFilesResponse(data, object, )
        OpenAPI.validate_property(ListFilesResponse, Symbol("data"), data)
        OpenAPI.validate_property(ListFilesResponse, Symbol("object"), object)
        return new(data, object, )
    end
end # type ListFilesResponse

const _property_types_ListFilesResponse = Dict{Symbol,String}(Symbol("data")=>"Vector{OpenAIFile}", Symbol("object")=>"String", )
OpenAPI.property_type(::Type{ ListFilesResponse }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ListFilesResponse[name]))}

function check_required(o::ListFilesResponse)
    o.data === nothing && (return false)
    o.object === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ ListFilesResponse }, name::Symbol, val)
    if name === Symbol("object")
        OpenAPI.validate_param(name, "ListFilesResponse", :enum, val, ["list"])
    end
end
