# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""AssistantToolsFunction

    AssistantToolsFunction(;
        type=nothing,
        var"function"=nothing,
    )

    - type::String : The type of tool being defined: &#x60;function&#x60;
    - var"function"::FunctionObject
"""
Base.@kwdef mutable struct AssistantToolsFunction <: OpenAPI.APIModel
    type::Union{Nothing, String} = nothing
    var"function" = nothing # spec type: Union{ Nothing, FunctionObject }

    function AssistantToolsFunction(type, var"function", )
        OpenAPI.validate_property(AssistantToolsFunction, Symbol("type"), type)
        OpenAPI.validate_property(AssistantToolsFunction, Symbol("function"), var"function")
        return new(type, var"function", )
    end
end # type AssistantToolsFunction

const _property_types_AssistantToolsFunction = Dict{Symbol,String}(Symbol("type")=>"String", Symbol("function")=>"FunctionObject", )
OpenAPI.property_type(::Type{ AssistantToolsFunction }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_AssistantToolsFunction[name]))}

function check_required(o::AssistantToolsFunction)
    o.type === nothing && (return false)
    o.var"function" === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ AssistantToolsFunction }, name::Symbol, val)
    if name === Symbol("type")
        OpenAPI.validate_param(name, "AssistantToolsFunction", :enum, val, ["function"])
    end
end
