# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""ChatCompletionRequestMessageContentPartText

    ChatCompletionRequestMessageContentPartText(;
        type=nothing,
        text=nothing,
    )

    - type::String : The type of the content part.
    - text::String : The text content.
"""
Base.@kwdef mutable struct ChatCompletionRequestMessageContentPartText <: OpenAPI.APIModel
    type::Union{Nothing, String} = nothing
    text::Union{Nothing, String} = nothing

    function ChatCompletionRequestMessageContentPartText(type, text, )
        OpenAPI.validate_property(ChatCompletionRequestMessageContentPartText, Symbol("type"), type)
        OpenAPI.validate_property(ChatCompletionRequestMessageContentPartText, Symbol("text"), text)
        return new(type, text, )
    end
end # type ChatCompletionRequestMessageContentPartText

const _property_types_ChatCompletionRequestMessageContentPartText = Dict{Symbol,String}(Symbol("type")=>"String", Symbol("text")=>"String", )
OpenAPI.property_type(::Type{ ChatCompletionRequestMessageContentPartText }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ChatCompletionRequestMessageContentPartText[name]))}

function check_required(o::ChatCompletionRequestMessageContentPartText)
    o.type === nothing && (return false)
    o.text === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ ChatCompletionRequestMessageContentPartText }, name::Symbol, val)
    if name === Symbol("type")
        OpenAPI.validate_param(name, "ChatCompletionRequestMessageContentPartText", :enum, val, ["text"])
    end
end
