# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

module OpenAIOpenAPI

using Dates, TimeZones
using OpenAPI
using OpenAPI.Clients

const API_VERSION = "2.0.0"

include("modelincludes.jl")

include("apis/api_AssistantsApi.jl")
include("apis/api_AudioApi.jl")
include("apis/api_ChatApi.jl")
include("apis/api_CompletionsApi.jl")
include("apis/api_EditsApi.jl")
include("apis/api_EmbeddingsApi.jl")
include("apis/api_FilesApi.jl")
include("apis/api_FineTunesApi.jl")
include("apis/api_FineTuningApi.jl")
include("apis/api_ImagesApi.jl")
include("apis/api_ModelsApi.jl")
include("apis/api_ModerationsApi.jl")

end # module OpenAIOpenAPI
